
build: lexical_helper.o comment_system.o line_splicing_system.o trigraph_system.o universal_character_system.o lexical_analyzer.o

lexical_helper.o:
	${CC} ${ARGS} -c lexical_helper.cpp
	
comment_system.o:
	${CC} ${ARGS} -c comment_system.cpp

line_splicing_system.o:
	${CC} ${ARGS} -c line_splicing_system.cpp

trigraph_system.o:
	${CC} ${ARGS} -c trigraph_system.cpp

universal_character_system.o:
	${CC} ${ARGS} -c universal_character_system.cpp

lexical_analyzer.o:
	${CC} ${ARGS} -c lexical_analyzer.cpp
